package interpreter;

//@author A0105912N
public enum CommandType {
    
    ADD, MODIFY,
    DISPLAY_NOW, DISPLAY_TODAY, DISPLAY_TOMORROW, DISPLAY_WEEK, DISPLAY_MONTH, DISPLAY_ALL, DISPLAY_IN_TIME, DISPLAY_ALL_FLOAT,
    
    DELETE, DELETE_ALL_COMPLETED,  
    SEARCH, MARK, UNMARK, 
    
    QUIT, CLEAR, UNDO, REDO,
    
    EXPORT, IMPORT,
    
    INVALID
    
}
