
public enum CommandFeedback {
    
	INVALID_DESCRIPTION, INVALID_LOCATION, INVALID_PRIORITY, INVALID_FOLDER_REF,
	
	INVALID_TIME_HR, INVALID_TIME_MIN, INVALID_TIME_AMPM, 
	INVALID_DATE_DAY, INVALID_DATE_MONTH, INVALID_DATE_YEAR, 
	
	INVALID_DISPLAY_REF, INVALID_DELETE_REF, CANNOT_UNDO, CANNOT_REDO,
	INVALID_MARK_REF, SEARCH_NOT_FOUND, 
	
	CONTEXT_INVALID, // Must add/modify
		
	INVALID_COMMAND_FORMAT, INVALID_COMMAND, INVALID_ALREADY_EXISTS,
	MISSING_QUOTES, MISSING_INFO, 
	
	INVALID_DATABASE,
	
	SUCCESSFUL_OPERATION;
}


