public enum CommandFeedback {
    
    	INVALID_TIME, INVALID_PRIORITY, INVALID_FOLDER_REF,
	
	INVALID_DISPLAY_REF, INVALID_DELETE_REF, CANNOT_UNDO, CANNOT_REDO,
	INVALID_MARK_REF, SEARCH_NOT_FOUND, 
	
	CONTEXT_INVALID, // Must add/modify
		
	INVALID_COMMAND_FORMAT, INVALID_COMMAND, INVALID_ALREADY_EXISTS,
	MISSING_QUOTES, MISSING_INFO, 
	
	INVALID_DATABASE_DUPLICATES,
	
	SUCCESSFUL_OPERATION;
}


