package interpreter;

//@author A0105912N
public enum CommandFeedback {
    
    INVALID_START_TIME, INVALID_END_TIME, INVALID_REMIND_TIME, 
    INVALID_PRIORITY, INVALID_FOLDER_REF, INVALID_TASK_ID,
    
    EMPTY_DESCRIPTION, EMPTY_LOCATION,
    
    INVALID_DATABASE_DUPLICATES, EMPTY_KEYWORD, MULTIPLE_WORD_KEYWORD,
    
    SUCCESSFUL_OPERATION;
}

